name: Studio - OpenAPI Mock Tests
on:
  workflow_dispatch:
    inputs:
      enterprise_artifact_url:
        description: Specmatic Enterprise snapshot JAR URL
        required: false
        type: string
      orchestrator_disable_visual: ${{ inputs.orchestrator_disable_visual }}
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  run-mock-server:
    uses: ./.github/workflows/playwright-test-group.yml
    with:
      test_path: specs/openapi/run-mock-server
      artifact_name: run-mock-server
      group_name: Mock
      enterprise_artifact_url: ${{ inputs.enterprise_artifact_url || '' }}
      orchestrator_disable_visual: ${{ inputs.orchestrator_disable_visual }}
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
      SPECMATIC_LICENSE_KEY: ${{ secrets.SPECMATIC_LICENSE_KEY }}
