name: Studio - OpenAPI Spec Tests
on:
  push:
    branches: [main, master, invalid-spec-tests]
  pull_request:
    branches: [main, master]
jobs:
  update-service-spec:
    uses: ./.github/workflows/playwright-test-group.yml
    with:
      test_path: specs/openapi/update-service-spec
      artifact_name: update-service-spec
      group_name: Spec
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
      SPECMATIC_LICENSE_KEY: ${{ secrets.SPECMATIC_LICENSE_KEY }}
