name: Studio - Async Mock Tests
on:
  push:
    branches: [main, master, invalid-spec-tests]
  pull_request:
    branches: [main, master]

jobs:
  run-async-mock-server:
    uses: ./.github/workflows/playwright-test-group.yml
    with:
      test_path: specs/async/run-mock-server
      artifact_name: run-async-mock-server
      group_name: Async Mock
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
      SPECMATIC_LICENSE_KEY: ${{ secrets.SPECMATIC_LICENSE_KEY }}
