name: Studio - OpenAPI Contract Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  execute-contract-tests:
    uses: ./.github/workflows/playwright-test-group.yml
    with:
      test_path: specs/openapi/execute-contract-tests
      artifact_name: execute-contract-tests
      group_name: Contract
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
      SPECMATIC_LICENSE_KEY: ${{ secrets.SPECMATIC_LICENSE_KEY }}
