name: Studio - Async Contract Tests
on:
  push:
    branches: [main, master, invalid-spec-tests]
  pull_request:
    branches: [main, master]

jobs:
  execute-async-contract-tests:
    uses: ./.github/workflows/playwright-test-group.yml
    with:
      test_path: specs/async/execute-contract-tests
      artifact_name: execute-contract-tests-async
      group_name: Async Contract
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
      SPECMATIC_LICENSE_KEY: ${{ secrets.SPECMATIC_LICENSE_KEY }}
